// lib/disclosures.ts
// Canonical disclosure lines — used on ALL report surfaces, white-label or HomeRates-branded.
// These are data attribution requirements and educational disclaimers that travel with
// the content, not with the brand. Never strip these from white-label builds.

export const EDUCATIONAL_DISCLAIMER =
  'HomeRates.ai is an independent educational tool — not a financial advisor, mortgage lender, or broker. ' +
  'All estimates (PITI, AVM, income thresholds, Decision Scores) are statistical models and may differ from actual outcomes. ' +
  'Not a loan offer, pre-approval, or commitment to lend.';

export const DATA_ATTRIBUTION =
  'Powered by FRED® Data — Federal Reserve Bank of St. Louis. ' +
  'Intelligence pipeline: multi-model AI orchestration — OpenAI · Grok by xAI · Claude by Anthropic.';

// Combined single line used in footers and disclosures sections
export const FULL_DISCLOSURE = `${EDUCATIONAL_DISCLAIMER} ${DATA_ATTRIBUTION}`;

// Short version for tight spaces (bottom of cards, small print)
export const SHORT_DISCLOSURE =
  'Educational estimates only — not financial advice or a commitment to lend. ' +
  'Powered by FRED® · OpenAI · Grok by xAI · Claude by Anthropic.';

// ─── AI-origin disclosure (Fannie Mae LL-2026-04, effective 2026-08-06) ────────
// Required wherever free-form AI-GENERATED NARRATIVE reaches a consumer — chat
// answers, property/market commentary, negotiation-style write-ups, welcome-back
// summaries. Distinct from EDUCATIONAL_DISCLAIMER above: that one says "this
// number may be wrong"; this one says "a model wrote these words, not a human."
//
// Does NOT apply to deterministic calculated output shown as numbers/tables/
// charts (LLPA breakdown, PITI, DSCR, rate curves, Decision Scores,
// buildNegotiationBrief()'s output) — those are pure code, no model call, and
// carrying this label on them would be inaccurate, not just unnecessary.
// See the 2026-08-06 AI-narration audit for the full surface-by-surface scoping
// before adding this to a new surface — some fields are hybrid (deterministic
// template with embedded AI-chosen words) and need per-field judgment, not a
// blanket component wrap.
export const AI_GENERATED_LABEL = 'AI-generated';

export const AI_GENERATED_TOOLTIP =
  'This explanation is written by AI based on the data shown. Scores, rates, and other numbers ' +
  'above are calculated separately by deterministic math — never generated by AI.';
